services:
  dev:
    image: a1-sdk-builder:latest
    container_name: A1_Builder
    command: ["/bin/bash", "-lc", "sleep infinity"]
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ../data/A1_SDK_SC132GS:/app/data/A1_SDK_SC132GS
      - ../src:/app/src
      - ../scripts:/app/scripts
      - ../models:/app/models
      - ../output:/app/output
    working_dir: /app
    ports:
      - "8080:8080"
